name: BUILD CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: ./build-run.sh
    - name: test
      run: ./build-run.sh -t
    - name: benchmark
      run: ./build-run.sh -b

