name: BUILD CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: ./build.sh -t -b
    - name: test
      run: ./run-executable.sh build html-parser-tests-Release
    - name: benchmark
      run: ./run-executable.sh build html-parser-benchmarks-Release

