name: Memory Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install possible submodules
      run: git submodule update --init --recursive

    - name: Install Valgrind
      run: |
          sudo apt-get update -q
          sudo apt-get install -y valgrind

    - name: Build
      run: ./build.sh -t -b

    - name: Memory check tests
      run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 --track-origins=yes build/tests/html-parser-tests-Release

    - name: Memory check benchmarks
      run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 --track-origins=yes build/benchmarks/html-parser-benchmarks-Release

