name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create libs dir
      run: mkdir libs

    - name: Install util library
      run: |
        cd libs
        git clone https://github.com/florianmarkusse/util.git
        cd util
        ./build.sh
        cd ../../

    - name: Build
      run: ./build.sh -t -b

    - name: Test
      run: build/tests/html-parser-tests-Release

    - name: Benchmark
      run: build/benchmarks/html-parser-benchmarks-Release

